name: build and push image to docker hub

on: push
jobs:
  push_to_registry:
     name: push Docker image to Docker Hub
     runs-on: ubuntu-latest
     steps:
      - name: check out the repo
        uses: actions/checkout@v3

        - name: login to docekr hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push docker image
              uses: docker/build-push-action@v4
              with:
                context: Dockerfilefolder
                Push: true
                tags: sujinaa/testrepo:latest